[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm build --filter=api"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "heal-api"
